Met à jour python et toutes les dépendances
openfisca/openfisca-paris pull request #145
Opened 2023-06-19 13:19 UTC by Allan-CodeWorks

# Description
## Breaking changes
- Met à jour la version minimale de `python` de `3.7`  vers python `3.9`
- Met à jour la version minimale d'`openfisca-core` de `35.2.0` vers `40.0.0`
- Met à jour la version minimale d'`openfisca-france`de `102`  vers `149.0.0`

2023-06-19 13:33 UTC, benjello requested changes
J'attendrais la publication de la version 149.1.1 de `openfisca-france` avant de fusionner cette PR.

2023-06-19 13:33 UTC, benjello commented on setup.py
> +        'OpenFisca-France >= 149, < 150',
```suggestion
        'OpenFisca-France >= 149.1.1, < 150',
```

2023-06-21 08:47 UTC, Allan-CodeWorks commented on setup.py
> +        'OpenFisca-France >= 149, < 150',
J'ai aussi passé la version minimale d'`openfisca-core`en `40.0.1` pour être raccord

2023-06-26 17:14 UTC, benjello approved these changes

2023-06-27 07:58 UTC, merged